from __future__ import annotations

import os
import sys
from datetime import datetime, timezone

from config.settings import settings
from modules.comms_platform_targets import platform_working_target, remember_platform_working_target, working_target_matches_task
from modules.comms_text_utils import extract_topic_from_request
from modules.task_lineage import ensure_task_lineage
from modules.workflow_recipe_executor import WorkflowRecipeExecutor
from modules.workflow_recipes import get_workflow_recipe


def _agent_module(agent):
    return sys.modules.get(getattr(agent.__class__, "__module__", "") or "")


def _resolve_hook(agent, name: str, default):
    module = _agent_module(agent)
    if module is not None and hasattr(module, name):
        return getattr(module, name)
    return default


def build_recipe_payload(agent, recipe_name: str, *, live: bool, request_text: str = "") -> tuple[str, dict]:
    from modules.platform_artifact_pack import build_platform_bundle

    rec = get_workflow_recipe(recipe_name)
    if not rec:
        raise ValueError(f"recipe_not_found:{recipe_name}")
    platform = str(rec.get("platform") or "").strip().lower()
    run_tag = datetime.now(timezone.utc).strftime("%m%d-%H%M%S")
    working_target_fn = _resolve_hook(agent, "_platform_working_target", platform_working_target)
    working_target = working_target_fn(platform)
    active_owner_task = agent._owner_task_state.get_active() if agent._owner_task_state else None
    lineage_fn = _resolve_hook(agent, "ensure_task_lineage", ensure_task_lineage)
    task_root_id, artifact_ids = lineage_fn(active_owner_task, request_text or recipe_name)
    if agent._owner_task_state and active_owner_task and not str(active_owner_task.get("task_root_id") or "").strip():
        try:
            agent._owner_task_state.enrich_active(task_root_id=task_root_id, **artifact_ids)
        except Exception:
            pass
    topic = extract_topic_from_request(request_text, "Digital Product Kit")
    base_title = topic if len(topic) >= 8 else f"Working Draft {run_tag}: Digital Product Kit"

    payload: dict = {
        "dry_run": not live,
        "fresh_artifacts_only": True,
        "run_tag": run_tag,
        "task_root_id": task_root_id,
        "project_id": artifact_ids.get("project_id", ""),
        "listing_work_id": artifact_ids.get("listing_id", ""),
        "research_work_id": artifact_ids.get("research_id", ""),
        "content_work_id": artifact_ids.get("content_id", ""),
        "seo_work_id": artifact_ids.get("seo_id", ""),
        "publish_work_id": artifact_ids.get("publish_id", ""),
        "metadata_work_id": artifact_ids.get("metadata_id", ""),
        "title": base_title[:140],
        "name": base_title[:140],
        "content": "Structured product content with clear value, searchable keywords, and a concise CTA.",
        "text": f"{base_title}: SEO-ready digital product workflow with proof checks.",
        "description": (
            "SEO-ready test listing generated by VITO. Includes structured benefits, target audience, "
            "delivery format, usage steps, and optimization notes for marketplace conversion."
        ),
        "summary": "SEO-ready AI digital product test listing.",
        "price": 5,
        "category": "Digital",
        "tags": ["ai", "automation", "digital product", "templates", "productivity"],
        "seo_title": "Digital Product Kit for Creators",
        "seo_description": "SEO-optimized listing prepared for marketplace conversion and workflow validation.",
        "url": "https://example.com/vito-test",
        "hashtags": ["#DigitalProduct", "#CreatorBusiness", "#OnlineSales"],
        "author": "Editorial Team",
        "subtitle": "Practical workflow kit for creators",
        "materials": ["pdf", "digital download", "instant download", "planner pages"],
        "preview_paths": [],
    }

    if platform == "reddit":
        uname = str(getattr(settings, "REDDIT_USERNAME", "") or "").strip()
        payload["subreddit"] = str(os.getenv("REDDIT_TEST_SUBREDDIT", f"u_{uname}" if uname else "test"))
        payload["text"] = (
            f"{base_title}. Research -> listing -> publish pipeline. "
            "Details: https://example.com/vito-test #Research #DigitalProduct"
        )
        payload["url"] = ""
        payload["image_url"] = ""
    if platform == "gumroad":
        target_slug = str(working_target.get("target_slug") or "").strip()
        match_fn = _resolve_hook(agent, "_working_target_matches_task", working_target_matches_task)
        reuse_existing = bool(target_slug) and match_fn(working_target, task_root_id)
        payload.update(
            {
                "allow_existing_update": reuse_existing,
                "owner_edit_confirmed": reuse_existing,
                "target_slug": target_slug if reuse_existing else "",
                "operation": "update" if reuse_existing else "create",
                "keep_unpublished": True,
            }
        )
    if platform == "etsy":
        target_listing_id = str(working_target.get("target_listing_id") or "").strip()
        match_fn = _resolve_hook(agent, "_working_target_matches_task", working_target_matches_task)
        if target_listing_id and match_fn(working_target, task_root_id):
            payload.update(
                {
                    "allow_existing_update": True,
                    "owner_edit_confirmed": True,
                    "target_listing_id": target_listing_id,
                    "operation": "update",
                }
            )
        payload["draft_only"] = True
        if not payload.get("operation"):
            payload["operation"] = "create"
    if platform == "amazon_kdp":
        target_document_id = str(working_target.get("target_document_id") or "").strip()
        match_fn = _resolve_hook(agent, "_working_target_matches_task", working_target_matches_task)
        if not match_fn(working_target, task_root_id):
            target_document_id = ""
        payload["operation"] = "update" if target_document_id else "create_or_update_draft"
        if target_document_id:
            payload.update(
                {
                    "allow_existing_update": True,
                    "owner_edit_confirmed": True,
                    "target_document_id": target_document_id,
                }
            )
    if platform == "twitter":
        payload["text"] = (
            f"{base_title} https://example.com/vito-test "
            "#DigitalProducts #CreatorBusiness #OnlineSales"
        )[:280]
    if platform == "kofi":
        target_product_id = str(working_target.get("target_product_id") or "").strip()
        match_fn = _resolve_hook(agent, "_working_target_matches_task", working_target_matches_task)
        if target_product_id and match_fn(working_target, task_root_id):
            payload.update(
                {
                    "allow_existing_update": True,
                    "owner_edit_confirmed": True,
                    "target_product_id": target_product_id,
                    "operation": "update",
                }
            )
    if platform == "printful":
        target_product_id = str(working_target.get("target_product_id") or "").strip()
        match_fn = _resolve_hook(agent, "_working_target_matches_task", working_target_matches_task)
        if not match_fn(working_target, task_root_id):
            target_product_id = ""
        payload.update(
            {
                "sync_product": {"name": base_title[:100]},
                "sync_variants": [],
                "operation": "update" if target_product_id else "create_or_update",
            }
        )
        if target_product_id:
            payload["target_product_id"] = target_product_id
    return platform, build_platform_bundle(platform, payload)


async def run_recipe_direct(agent, recipe_name: str, *, live: bool, request_text: str = "") -> dict:
    platform, payload = build_recipe_payload(agent, recipe_name, live=live, request_text=request_text)
    exe = WorkflowRecipeExecutor(agent._publisher_queue)
    out = await exe.run_once(recipe_name, payload, trace_id=f"tg_recipe_{recipe_name}")
    res = out.get("result") if isinstance(out.get("result"), dict) else {}
    sticky_id = str(
        res.get("listing_id")
        or res.get("product_id")
        or res.get("target_product_id")
        or res.get("document_id")
        or res.get("target_document_id")
        or res.get("post_id")
        or res.get("id")
        or ""
    ).strip()
    sticky_slug = str(res.get("slug") or "").strip()
    sticky_url = str(res.get("url") or "").strip()
    if str(out.get("status") or "").lower() == "accepted" or sticky_id or sticky_slug or sticky_url:
        remember_fn = _resolve_hook(agent, "_remember_platform_working_target", remember_platform_working_target)
        remember_fn(platform, res)
    return out
