from pathlib import Path

from modules.skill_registry import SkillRegistry


def test_skill_registry_register_and_list(tmp_path: Path):
    db = str(tmp_path / "skills.db")
    reg = SkillRegistry(sqlite_path=db)
    reg.register_skill(
        name="gumroad_publish_via_browser",
        category="listing_create",
        source="gumroad_platform",
        status="learned",
        notes="publish via browser with evidence",
    )
    rows = reg.list_skills(limit=10)
    assert len(rows) >= 1
    assert rows[0]["name"] == "gumroad_publish_via_browser"
    assert "compatibility" in rows[0]
    assert "tests_coverage" in rows[0]
    assert "risk_score" in rows[0]
    assert "acceptance_status" in rows[0]


def test_skill_registry_audit_coverage(tmp_path: Path):
    db = str(tmp_path / "skills.db")
    tests_dir = tmp_path / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    (tests_dir / "test_gumroad_publish.py").write_text("def test_x():\n    assert True\n", encoding="utf-8")

    reg = SkillRegistry(sqlite_path=db)
    reg.register_skill(
        name="gumroad_publish_via_browser",
        category="publish",
        source="gumroad_platform",
        status="learned",
        notes="safe notes",
    )
    audited = reg.audit_coverage(tests_root=str(tests_dir))
    assert audited >= 1
    skill = reg.get_skill("gumroad_publish_via_browser")
    assert skill is not None
    assert float(skill.get("tests_coverage", 0)) >= 0
    assert skill.get("compatibility") in {"stable", "review", "unknown"}


def test_skill_registry_acceptance_event(tmp_path: Path):
    db = str(tmp_path / "skills.db")
    reg = SkillRegistry(sqlite_path=db)
    reg.register_skill(
        name="self_improve:abc",
        category="self_improve",
        source="vito_core",
        status="learned",
        notes="generated by self improve",
        acceptance_status="pending",
    )
    reg.accept_skill(
        name="self_improve:abc",
        tests_passed=True,
        evidence="reports/test_ok.md",
        validator="pytest",
        notes="all green",
    )
    row = reg.get_skill("self_improve:abc")
    assert row is not None
    assert row.get("acceptance_status") == "accepted"
    assert row.get("status") == "learned"


def test_skill_registry_pending_and_auto_accept(tmp_path: Path):
    db = str(tmp_path / "skills.db")
    reg = SkillRegistry(sqlite_path=db)
    reg.register_skill("s1", category="x", source="u", acceptance_status="pending")
    reg.register_skill("s2", category="x", source="u", acceptance_status="pending")
    pending = reg.pending_skills(limit=10)
    assert len(pending) >= 2
    changed = reg.auto_accept_pending(tests_passed=True, evidence="report.md", validator="pytest")
    assert changed >= 2
    assert reg.get_skill("s1").get("acceptance_status") == "accepted"


def test_skill_registry_remediation_tasks(tmp_path: Path):
    db = str(tmp_path / "skills.db")
    reg = SkillRegistry(sqlite_path=db)
    reg.register_skill(
        name="secret_skill",
        category="publish",
        source="vito_core",
        status="learned",
        notes="uses api token in notes",
    )
    reg.audit_coverage(tests_root=str(tmp_path / "tests"))
    rem = reg.remediate_high_risk(limit=10)
    assert rem.get("open_total", 0) >= 1
    open_tasks = reg.list_remediation_tasks(status="open", limit=10)
    assert any(t.get("skill_name") == "secret_skill" for t in open_tasks)

    reg.accept_skill("secret_skill", tests_passed=True, evidence="reports/ok.md")
    open_after = reg.list_remediation_tasks(status="open", limit=10)
    closed_after = reg.list_remediation_tasks(status="closed", limit=10)
    assert not any(t.get("skill_name") == "secret_skill" for t in open_after)
    assert any(t.get("skill_name") == "secret_skill" for t in closed_after)


def test_skill_registry_register_from_capability_packs(tmp_path: Path):
    db = str(tmp_path / "skills.db")
    packs = tmp_path / "capability_packs" / "pack_a"
    packs.mkdir(parents=True, exist_ok=True)
    (packs / "spec.json").write_text(
        """{
  "name": "pack_a",
  "category": "transport",
  "description": "transport routing pack",
  "acceptance_status": "pending"
}
""",
        encoding="utf-8",
    )
    reg = SkillRegistry(sqlite_path=db)
    count = reg.register_from_capability_packs(root=str(tmp_path / "capability_packs"))
    assert count == 1
    row = reg.get_skill("pack_a")
    assert row is not None
    assert row.get("category") == "transport"
    assert row.get("acceptance_status") == "pending"
