import os
from pathlib import Path

from dotenv import load_dotenv
from config.paths import root_path

ENV_PATH = Path(root_path(".env"))
load_dotenv(ENV_PATH)


class Settings:
    # LLM API Keys
    ANTHROPIC_API_KEY: str = os.getenv("ANTHROPIC_API_KEY", "")
    OPENAI_API_KEY: str = os.getenv("OPENAI_API_KEY", "")
    GOOGLE_API_KEY: str = os.getenv("GOOGLE_API_KEY", "")
    GEMINI_API_KEY: str = os.getenv("GEMINI_API_KEY", "")
    PERPLEXITY_API_KEY: str = os.getenv("PERPLEXITY_API_KEY", "")
    OPENROUTER_API_KEY: str = os.getenv("OPENROUTER_API_KEY", "")
    OPENROUTER_DEFAULT_MODEL: str = os.getenv("OPENROUTER_DEFAULT_MODEL", "openai/gpt-4o-mini")
    ANTICAPTCHA_KEY: str = os.getenv("ANTICAPTCHA_KEY", "")

    # Telegram
    TELEGRAM_BOT_TOKEN: str = os.getenv("TELEGRAM_BOT_TOKEN", "")
    TELEGRAM_OWNER_CHAT_ID: str = os.getenv("TELEGRAM_OWNER_CHAT_ID", "")
    AUTH_BROKER_STATE_FILE: str = os.getenv("AUTH_BROKER_STATE_FILE", "runtime/auth_broker_state.json")
    AUTH_SESSION_TTL_SEC: int = int(os.getenv("AUTH_SESSION_TTL_SEC", "10800") or 10800)
    AUTH_PREFER_BROWSER_COOKIE: bool = os.getenv("AUTH_PREFER_BROWSER_COOKIE", "true").lower() in ("1", "true", "yes", "on")
    MCP_TOOL_SCOPING_ENABLED: bool = os.getenv("MCP_TOOL_SCOPING_ENABLED", "true").lower() in ("1", "true", "yes", "on")

    # Database
    DATABASE_URL: str = os.getenv("DATABASE_URL", "")
    CHROMA_PATH: str = os.getenv("CHROMA_PATH", root_path("memory", "chroma_db"))
    SQLITE_PATH: str = os.getenv("SQLITE_PATH", root_path("memory", "vito_local.db"))

    # Platforms
    GUMROAD_API_KEY: str = os.getenv("GUMROAD_API_KEY", "")
    GUMROAD_OAUTH_TOKEN: str = os.getenv("GUMROAD_OAUTH_TOKEN", "")
    GUMROAD_EMAIL: str = os.getenv("GUMROAD_EMAIL", "")
    GUMROAD_PASSWORD: str = os.getenv("GUMROAD_PASSWORD", "")
    GUMROAD_STORAGE_STATE_FILE: str = os.getenv("GUMROAD_STORAGE_STATE_FILE", "runtime/gumroad_storage_state.json")
    ETSY_API_KEY: str = os.getenv("ETSY_API_KEY", "")
    KOFI_API_KEY: str = os.getenv("KOFI_API_KEY", "")
    WORDPRESS_URL: str = os.getenv("WORDPRESS_URL", "")
    WORDPRESS_APP_PASSWORD: str = os.getenv("WORDPRESS_APP_PASSWORD", "")
    MEDIUM_TOKEN: str = os.getenv("MEDIUM_TOKEN", "")

    # Email & Social
    GMAIL_ADDRESS: str = os.getenv("GMAIL_ADDRESS", "")
    GMAIL_PASSWORD: str = os.getenv("GMAIL_PASSWORD", "")
    SENDGRID_API_KEY: str = os.getenv("SENDGRID_API_KEY", "")
    REDDIT_CLIENT_ID: str = os.getenv("REDDIT_CLIENT_ID", "")
    REDDIT_CLIENT_SECRET: str = os.getenv("REDDIT_CLIENT_SECRET", "")
    REDDIT_USERNAME: str = os.getenv("REDDIT_USERNAME", "")
    REDDIT_PASSWORD: str = os.getenv("REDDIT_PASSWORD", "")
    REDDIT_USER_AGENT: str = os.getenv("REDDIT_USER_AGENT", "vito-bot/0.3")
    REDDIT_API_DISABLED: bool = os.getenv("REDDIT_API_DISABLED", "false").lower() in ("1", "true", "yes", "on")
    REDDIT_MODE: str = os.getenv("REDDIT_MODE", "api")

    # X.com (Twitter)
    TWITTER_MODE: str = os.getenv("TWITTER_MODE", "api")
    TWITTER_BEARER_TOKEN: str = os.getenv("TWITTER_BEARER_TOKEN", "")
    TWITTER_CONSUMER_KEY: str = os.getenv("TWITTER_CONSUMER_KEY", "")
    TWITTER_CONSUMER_SECRET: str = os.getenv("TWITTER_CONSUMER_SECRET", "")
    TWITTER_ACCESS_TOKEN: str = os.getenv("TWITTER_ACCESS_TOKEN", "")
    TWITTER_ACCESS_SECRET: str = os.getenv("TWITTER_ACCESS_SECRET", "")
    TWITTER_STORAGE_STATE_FILE: str = os.getenv("TWITTER_STORAGE_STATE_FILE", "runtime/twitter_storage_state.json")
    REDDIT_STORAGE_STATE_FILE: str = os.getenv("REDDIT_STORAGE_STATE_FILE", "runtime/reddit_storage_state.json")
    THREADS_STORAGE_STATE_FILE: str = os.getenv("THREADS_STORAGE_STATE_FILE", "runtime/threads_storage_state.json")
    PINTEREST_STORAGE_STATE_FILE: str = os.getenv("PINTEREST_STORAGE_STATE_FILE", "runtime/pinterest_storage_state.json")
    PINTEREST_ACCESS_TOKEN: str = os.getenv("PINTEREST_ACCESS_TOKEN", "")
    PINTEREST_MODE: str = os.getenv("PINTEREST_MODE", "browser")
    INSTAGRAM_STORAGE_STATE_FILE: str = os.getenv("INSTAGRAM_STORAGE_STATE_FILE", "runtime/instagram_storage_state.json")
    FACEBOOK_STORAGE_STATE_FILE: str = os.getenv("FACEBOOK_STORAGE_STATE_FILE", "runtime/facebook_storage_state.json")
    TIKTOK_STORAGE_STATE_FILE: str = os.getenv("TIKTOK_STORAGE_STATE_FILE", "runtime/tiktok_storage_state.json")
    LINKEDIN_STORAGE_STATE_FILE: str = os.getenv("LINKEDIN_STORAGE_STATE_FILE", "runtime/linkedin_storage_state.json")
    SHOPIFY_STORAGE_STATE_FILE: str = os.getenv("SHOPIFY_STORAGE_STATE_FILE", "runtime/shopify_storage_state.json")
    SUBSTACK_STORAGE_STATE_FILE: str = os.getenv("SUBSTACK_STORAGE_STATE_FILE", "runtime/substack_storage_state.json")
    CREATIVE_FABRICA_STORAGE_STATE_FILE: str = os.getenv("CREATIVE_FABRICA_STORAGE_STATE_FILE", "runtime/creative_fabrica_storage_state.json")
    YOUTUBE_STORAGE_STATE_FILE: str = os.getenv("YOUTUBE_STORAGE_STATE_FILE", "runtime/youtube_storage_state.json")
    GUMROAD_MODE: str = os.getenv("GUMROAD_MODE", "api")

    # Reddit RSS
    REDDIT_RSS_ENTREPRENEUR: str = os.getenv("REDDIT_RSS_ENTREPRENEUR", "")
    REDDIT_RSS_PASSIVE: str = os.getenv("REDDIT_RSS_PASSIVE", "")
    REDDIT_RSS_ECOMMERCE: str = os.getenv("REDDIT_RSS_ECOMMERCE", "")

    # New platforms
    PRINTFUL_API_KEY: str = os.getenv("PRINTFUL_API_KEY", "")
    PRINTFUL_STORE_ID: str = os.getenv("PRINTFUL_STORE_ID", "")
    PRINTFUL_MODE: str = os.getenv("PRINTFUL_MODE", "api")
    PRINTFUL_STORAGE_STATE_FILE: str = os.getenv("PRINTFUL_STORAGE_STATE_FILE", "runtime/printful_storage_state.json")
    ETSY_KEYSTRING: str = os.getenv("ETSY_KEYSTRING", "")
    ETSY_SHARED_SECRET: str = os.getenv("ETSY_SHARED_SECRET", "")
    ETSY_EMAIL: str = os.getenv("ETSY_EMAIL", "")
    ETSY_PASSWORD: str = os.getenv("ETSY_PASSWORD", "")
    ETSY_SHOP_ID: str = os.getenv("ETSY_SHOP_ID", "")
    ETSY_OAUTH_ACCESS_TOKEN: str = os.getenv("ETSY_OAUTH_ACCESS_TOKEN", "")
    ETSY_OAUTH_REFRESH_TOKEN: str = os.getenv("ETSY_OAUTH_REFRESH_TOKEN", "")
    ETSY_OAUTH_REDIRECT_URI: str = os.getenv("ETSY_OAUTH_REDIRECT_URI", "http://localhost:8765/callback")
    ETSY_MODE: str = os.getenv("ETSY_MODE", "api")
    ETSY_STORAGE_STATE_FILE: str = os.getenv("ETSY_STORAGE_STATE_FILE", "runtime/etsy_storage_state.json")
    GUMROAD_APP_ID: str = os.getenv("GUMROAD_APP_ID", "")
    GUMROAD_APP_SECRET: str = os.getenv("GUMROAD_APP_SECRET", "")
    KOFI_PAGE_ID: str = os.getenv("KOFI_PAGE_ID", "")
    CLOUDINARY_CLOUD_NAME: str = os.getenv("CLOUDINARY_CLOUD_NAME", "")
    CLOUDINARY_API_KEY: str = os.getenv("CLOUDINARY_API_KEY", "")
    CLOUDINARY_API_SECRET: str = os.getenv("CLOUDINARY_API_SECRET", "")

    # Image Generation
    REPLICATE_API_TOKEN: str = os.getenv("REPLICATE_API_TOKEN", "")
    BFL_API_KEY: str = os.getenv("BFL_API_KEY", "")
    WAVESPEED_API_KEY: str = os.getenv("WAVESPEED_API_KEY", "")

    # Social official APIs
    THREADS_ACCESS_TOKEN: str = os.getenv("THREADS_ACCESS_TOKEN", "")
    THREADS_USER_ID: str = os.getenv("THREADS_USER_ID", "")
    INSTAGRAM_ACCESS_TOKEN: str = os.getenv("INSTAGRAM_ACCESS_TOKEN", "")
    INSTAGRAM_BUSINESS_ACCOUNT_ID: str = os.getenv("INSTAGRAM_BUSINESS_ACCOUNT_ID", "")
    TIKTOK_ACCESS_TOKEN: str = os.getenv("TIKTOK_ACCESS_TOKEN", "")
    LINKEDIN_ACCESS_TOKEN: str = os.getenv("LINKEDIN_ACCESS_TOKEN", "")
    LINKEDIN_AUTHOR_URN: str = os.getenv("LINKEDIN_AUTHOR_URN", "")
    SHOPIFY_ACCESS_TOKEN: str = os.getenv("SHOPIFY_ACCESS_TOKEN", "")
    SHOPIFY_STORE_URL: str = os.getenv("SHOPIFY_STORE_URL", "")
    YOUTUBE_CLIENT_ID: str = os.getenv("YOUTUBE_CLIENT_ID", "")
    YOUTUBE_CLIENT_SECRET: str = os.getenv("YOUTUBE_CLIENT_SECRET", "")
    YOUTUBE_REFRESH_TOKEN: str = os.getenv("YOUTUBE_REFRESH_TOKEN", "")
    KDP_EMAIL: str = os.getenv("KDP_EMAIL", "")
    KDP_PASSWORD: str = os.getenv("KDP_PASSWORD", "")
    KDP_STORAGE_STATE_FILE: str = os.getenv("KDP_STORAGE_STATE_FILE", "runtime/kdp_storage_state.json")
    KDP_WATCHDOG_ENABLED: bool = os.getenv("KDP_WATCHDOG_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    KDP_WATCHDOG_BASE_HOURS: int = int(os.getenv("KDP_WATCHDOG_BASE_HOURS", "8") or 8)
    KDP_WATCHDOG_JITTER_MINUTES: int = int(os.getenv("KDP_WATCHDOG_JITTER_MINUTES", "30") or 30)
    KDP_WATCHDOG_STOP_ON_FAIL: bool = os.getenv("KDP_WATCHDOG_STOP_ON_FAIL", "true").lower() in ("1", "true", "yes", "on")
    KDP_WATCHDOG_STATE_PATH: str = os.getenv("KDP_WATCHDOG_STATE_PATH", "runtime/kdp_watchdog_state.json")
    KDP_AUTH_FORCE_FRESH_EACH_LOGIN: bool = os.getenv("KDP_AUTH_FORCE_FRESH_EACH_LOGIN", "false").lower() in ("1", "true", "yes", "on")

    # Financial limits (USD)
    # Hierarchy: OPERATION_MAX < OPERATION_NOTIFY < DAILY_LIMIT < OPERATION_APPROVE
    DAILY_LIMIT_USD: float = float(os.getenv("DAILY_LIMIT_USD", "3"))
    OPERATION_NOTIFY_USD: float = float(os.getenv("OPERATION_NOTIFY_USD", "1"))
    OPERATION_APPROVE_USD: float = float(os.getenv("OPERATION_APPROVE_USD", "20"))
    OPERATION_MAX_USD: float = float(os.getenv("OPERATION_MAX_USD", "2"))

    # Autonomy profile (relaxed mode for owner-controlled environment)
    AUTONOMY_MAX_MODE: bool = os.getenv("AUTONOMY_MAX_MODE", "false").lower() in ("1", "true", "yes", "on")
    AUTONOMY_REQUIRE_PUBLISH_APPROVAL: bool = os.getenv("AUTONOMY_REQUIRE_PUBLISH_APPROVAL", "true").lower() in ("1", "true", "yes", "on")
    AUTONOMY_ECOMMERCE_APPROVAL_REQUIRED: bool = os.getenv("AUTONOMY_ECOMMERCE_APPROVAL_REQUIRED", "true").lower() in ("1", "true", "yes", "on")
    AUTONOMY_DISABLE_PUBLISH_COOLDOWNS: bool = os.getenv("AUTONOMY_DISABLE_PUBLISH_COOLDOWNS", "false").lower() in ("1", "true", "yes", "on")
    AUTONOMY_DISABLE_PUBLISH_DUPLICATE_BLOCK: bool = os.getenv("AUTONOMY_DISABLE_PUBLISH_DUPLICATE_BLOCK", "false").lower() in ("1", "true", "yes", "on")
    AUTONOMY_ALLOW_EXISTING_PRODUCT_UPDATE: bool = os.getenv("AUTONOMY_ALLOW_EXISTING_PRODUCT_UPDATE", "false").lower() in ("1", "true", "yes", "on")
    AUTONOMY_ACCEPT_INTERMEDIATE_PUBLISH_STATUSES: bool = os.getenv("AUTONOMY_ACCEPT_INTERMEDIATE_PUBLISH_STATUSES", "false").lower() in ("1", "true", "yes", "on")
    AUTONOMY_AUTO_EXECUTE_REQUESTS: bool = os.getenv("AUTONOMY_AUTO_EXECUTE_REQUESTS", "false").lower() in ("1", "true", "yes", "on")
    AUTONOMY_AUTO_LEARN_ON_FAILURE: bool = os.getenv("AUTONOMY_AUTO_LEARN_ON_FAILURE", "true").lower() in ("1", "true", "yes", "on")
    AUTONOMY_AUTO_SELF_IMPROVE_ON_MISS: bool = os.getenv("AUTONOMY_AUTO_SELF_IMPROVE_ON_MISS", "false").lower() in ("1", "true", "yes", "on")

    # Autonomy toggles
    PROACTIVE_ENABLED: bool = os.getenv("PROACTIVE_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    BRAINSTORM_WEEKLY: bool = os.getenv("BRAINSTORM_WEEKLY", "true").lower() in ("1", "true", "yes", "on")
    VITO_EVOLUTION_ENABLED: bool = os.getenv("VITO_EVOLUTION_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    EVOLUTION_DISCOVERY_ENABLED: bool = os.getenv("EVOLUTION_DISCOVERY_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    EVOLUTION_DISCOVERY_INTERVAL_TICKS: int = int(os.getenv("EVOLUTION_DISCOVERY_INTERVAL_TICKS", "2016") or 2016)
    EVOLUTION_DISCOVERY_QUERIES: str = os.getenv(
        "EVOLUTION_DISCOVERY_QUERIES",
        "python autonomous agents memory benchmark runtime;python browser automation resilience;python self-healing sandbox patch apply",
    )
    EVOLUTION_OVERSEER_ENABLED: bool = os.getenv("EVOLUTION_OVERSEER_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    EVOLUTION_OVERSEER_INTERVAL_TICKS: int = int(os.getenv("EVOLUTION_OVERSEER_INTERVAL_TICKS", "72") or 72)
    EVOLUTION_OVERSEER_STUCK_TICKS: int = int(os.getenv("EVOLUTION_OVERSEER_STUCK_TICKS", "288") or 288)
    EVOLUTION_AUDIT_SECRET: str = os.getenv("EVOLUTION_AUDIT_SECRET", "")
    EVOLUTION_SANDBOX_ALLOWED_ENV: str = os.getenv("EVOLUTION_SANDBOX_ALLOWED_ENV", "PATH,HOME,LANG,LC_ALL,PYTHONPATH,VIRTUAL_ENV,TZ")

    # LLM cache
    LLM_CACHE_TTL_HOURS: int = int(os.getenv("LLM_CACHE_TTL_HOURS", "24"))
    LLM_DISABLED_MODELS: str = os.getenv("LLM_DISABLED_MODELS", "")
    LLM_ENABLED_MODELS: str = os.getenv("LLM_ENABLED_MODELS", "")
    LLM_ROUTER_MODE: str = os.getenv("LLM_ROUTER_MODE", "prod")
    LLM_FORCE_GEMINI_FREE: bool = os.getenv("LLM_FORCE_GEMINI_FREE", "false").lower() in ("1", "true", "yes", "on")
    LLM_FORCE_GEMINI_MODEL: str = os.getenv("LLM_FORCE_GEMINI_MODEL", "gemini-2.5-flash")
    RESEARCH_ROUTER_MODE: str = os.getenv("RESEARCH_ROUTER_MODE", "test")
    GEMINI_FREE_MAX_RPM: int = int(os.getenv("GEMINI_FREE_MAX_RPM", "15") or 15)
    LLM_RATE_LIMIT_GOOGLE_RPM: int = int(os.getenv("LLM_RATE_LIMIT_GOOGLE_RPM", "15") or 15)
    LLM_RATE_LIMIT_OPENAI_RPM: int = int(os.getenv("LLM_RATE_LIMIT_OPENAI_RPM", "60") or 60)
    LLM_RATE_LIMIT_ANTHROPIC_RPM: int = int(os.getenv("LLM_RATE_LIMIT_ANTHROPIC_RPM", "60") or 60)
    LLM_RATE_LIMIT_PERPLEXITY_RPM: int = int(os.getenv("LLM_RATE_LIMIT_PERPLEXITY_RPM", "30") or 30)
    LLM_RATE_LIMIT_OPENROUTER_RPM: int = int(os.getenv("LLM_RATE_LIMIT_OPENROUTER_RPM", "60") or 60)
    LLM_RATE_LIMIT_MAX_WAIT_SEC: int = int(os.getenv("LLM_RATE_LIMIT_MAX_WAIT_SEC", "60") or 60)
    GEMINI_FREE_TEXT_RPD: int = int(os.getenv("GEMINI_FREE_TEXT_RPD", "1000") or 1000)
    GEMINI_FREE_SEARCH_RPD: int = int(os.getenv("GEMINI_FREE_SEARCH_RPD", "1500") or 1500)
    GEMINI_ENABLE_GROUNDING_SEARCH: bool = os.getenv("GEMINI_ENABLE_GROUNDING_SEARCH", "true").lower() in ("1", "true", "yes", "on")
    GEMINI_ENABLE_URL_CONTEXT: bool = os.getenv("GEMINI_ENABLE_URL_CONTEXT", "true").lower() in ("1", "true", "yes", "on")
    GEMINI_EMBEDDINGS_ENABLED: bool = os.getenv("GEMINI_EMBEDDINGS_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    GEMINI_EMBED_MODEL: str = os.getenv("GEMINI_EMBED_MODEL", "gemini-embedding-001")
    MEM0_ENABLED: bool = os.getenv("MEM0_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    MEM0_API_KEY: str = os.getenv("MEM0_API_KEY", "")
    MEM0_USER_ID: str = os.getenv("MEM0_USER_ID", "vito_owner")
    MEM0_COLLECTION: str = os.getenv("MEM0_COLLECTION", "vito_runtime")
    GEMINI_ENABLE_IMAGEN: bool = os.getenv("GEMINI_ENABLE_IMAGEN", "false").lower() in ("1", "true", "yes", "on")
    GEMINI_IMAGEN_MODEL: str = os.getenv("GEMINI_IMAGEN_MODEL", "imagen-3.0-generate-002")
    GEMINI_LIVE_API_ENABLED: bool = os.getenv("GEMINI_LIVE_API_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    IMAGE_ROUTER_PREFER_GEMINI: bool = os.getenv("IMAGE_ROUTER_PREFER_GEMINI", "false").lower() in ("1", "true", "yes", "on")
    RESEARCH_URL_CONTEXT_ENABLED: bool = os.getenv("RESEARCH_URL_CONTEXT_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    RESEARCH_URL_CONTEXT_MAX_URLS: int = int(os.getenv("RESEARCH_URL_CONTEXT_MAX_URLS", "4") or 4)
    RESEARCH_URL_CONTEXT_MAX_CHARS_PER_URL: int = int(os.getenv("RESEARCH_URL_CONTEXT_MAX_CHARS_PER_URL", "2500") or 2500)
    MODEL_ACTIVE_PROFILE: str = os.getenv("MODEL_ACTIVE_PROFILE", "balanced")

    # Notifications
    NOTIFY_MODE: str = os.getenv("NOTIFY_MODE", "minimal")  # minimal|all
    TELEGRAM_CRON_ENABLED: bool = os.getenv("TELEGRAM_CRON_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    TELEGRAM_STRICT_COMMANDS: bool = os.getenv("TELEGRAM_STRICT_COMMANDS", "true").lower() in ("1", "true", "yes", "on")
    OWNER_AUTO_APPROVE_GOALS: bool = os.getenv("OWNER_AUTO_APPROVE_GOALS", "true").lower() in ("1", "true", "yes", "on")
    PLATFORM_RULES_SYNC_ENABLED: bool = os.getenv("PLATFORM_RULES_SYNC_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    PLATFORM_RULES_SYNC_INTERVAL_TICKS: int = int(os.getenv("PLATFORM_RULES_SYNC_INTERVAL_TICKS", "288") or 288)
    PLATFORM_RULES_SYNC_SERVICES: str = os.getenv(
        "PLATFORM_RULES_SYNC_SERVICES",
        "gumroad,etsy,kofi,printful,reddit,pinterest,amazon_kdp,twitter",
    )

    # Browser behavior
    BROWSER_DEFAULT_ON_URL: bool = os.getenv("BROWSER_DEFAULT_ON_URL", "true").lower() in ("1", "true", "yes", "on")
    BROWSER_CONSTRAINED_MODE: bool = os.getenv("BROWSER_CONSTRAINED_MODE", "true").lower() in ("1", "true", "yes", "on")
    BROWSER_SAFE_MODE_ENABLED: bool = os.getenv("BROWSER_SAFE_MODE_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    BROWSER_MIN_ACTION_DELAY_MS: int = int(os.getenv("BROWSER_MIN_ACTION_DELAY_MS", "180") or 180)
    BROWSER_MAX_ACTION_DELAY_MS: int = int(os.getenv("BROWSER_MAX_ACTION_DELAY_MS", "700") or 700)
    BROWSER_DOMAIN_COOLDOWN_MS: int = int(os.getenv("BROWSER_DOMAIN_COOLDOWN_MS", "1200") or 1200)
    PLATFORM_CIRCUIT_BREAKER_FAIL_THRESHOLD: int = int(os.getenv("PLATFORM_CIRCUIT_BREAKER_FAIL_THRESHOLD", "3") or 3)
    PLATFORM_CIRCUIT_BREAKER_COOLDOWN_SEC: int = int(os.getenv("PLATFORM_CIRCUIT_BREAKER_COOLDOWN_SEC", "1800") or 1800)
    PLATFORM_CIRCUIT_BREAKER_LONG_COOLDOWN_SEC: int = int(os.getenv("PLATFORM_CIRCUIT_BREAKER_LONG_COOLDOWN_SEC", "21600") or 21600)
    BROWSER_NAV_RETRY_MAX: int = int(os.getenv("BROWSER_NAV_RETRY_MAX", "2") or 2)
    BROWSER_NAV_RETRY_BACKOFF_MS: int = int(os.getenv("BROWSER_NAV_RETRY_BACKOFF_MS", "900") or 900)
    BROWSER_CHALLENGE_DETECT_ENABLED: bool = os.getenv("BROWSER_CHALLENGE_DETECT_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    BROWSER_CHALLENGE_BLOCK_MODE: bool = os.getenv("BROWSER_CHALLENGE_BLOCK_MODE", "true").lower() in ("1", "true", "yes", "on")
    BROWSER_CHALLENGE_KEYWORDS: str = os.getenv(
        "BROWSER_CHALLENGE_KEYWORDS",
        "captcha,challenge,verify you are human,robot check,access denied,temporarily blocked,unusual traffic",
    )
    PUBLISH_CREATE_GUARD_ENABLED: bool = os.getenv("PUBLISH_CREATE_GUARD_ENABLED", "true").lower() in ("1", "true", "yes", "on")

    # Owner inbox (file-based comms)
    OWNER_INBOX_ENABLED: bool = os.getenv("OWNER_INBOX_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    CONVERSATION_HISTORY_PATH: str = os.getenv("CONVERSATION_HISTORY_PATH", root_path("runtime", "conversation_history.json"))
    CANCEL_STATE_PATH: str = os.getenv("CANCEL_STATE_PATH", root_path("runtime", "cancel_state.json"))
    OWNER_TASK_STATE_PATH: str = os.getenv("OWNER_TASK_STATE_PATH", root_path("runtime", "owner_task_state.json"))
    CONVERSATION_CONTEXT_TURNS: int = int(os.getenv("CONVERSATION_CONTEXT_TURNS", "20") or 20)
    REVENUE_ENGINE_ENABLED: bool = os.getenv("REVENUE_ENGINE_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    REVENUE_ENGINE_DRY_RUN: bool = os.getenv("REVENUE_ENGINE_DRY_RUN", "true").lower() in ("1", "true", "yes", "on")
    REVENUE_ENGINE_REQUIRE_APPROVAL: bool = os.getenv("REVENUE_ENGINE_REQUIRE_APPROVAL", "false").lower() in ("1", "true", "yes", "on")
    REVENUE_ENGINE_DAILY_HOUR_UTC: int = int(os.getenv("REVENUE_ENGINE_DAILY_HOUR_UTC", "15") or 15)
    REVENUE_ENGINE_LIVE_REQUIRE_AUTH: bool = os.getenv("REVENUE_ENGINE_LIVE_REQUIRE_AUTH", "true").lower() in ("1", "true", "yes", "on")
    REVENUE_ENGINE_LIVE_CHECK_ADAPTER_AUTH: bool = os.getenv("REVENUE_ENGINE_LIVE_CHECK_ADAPTER_AUTH", "true").lower() in ("1", "true", "yes", "on")
    REVENUE_ENGINE_LIVE_AUTH_TIMEOUT_SEC: int = int(os.getenv("REVENUE_ENGINE_LIVE_AUTH_TIMEOUT_SEC", "12") or 12)
    REVENUE_ENGINE_LIVE_MAX_QUEUE_FAILED: int = int(os.getenv("REVENUE_ENGINE_LIVE_MAX_QUEUE_FAILED", "0") or 0)
    REVENUE_ENGINE_LIVE_MAX_QUEUE_QUEUED: int = int(os.getenv("REVENUE_ENGINE_LIVE_MAX_QUEUE_QUEUED", "20") or 20)
    REVENUE_ENGINE_LIVE_MAX_QUEUE_RUNNING: int = int(os.getenv("REVENUE_ENGINE_LIVE_MAX_QUEUE_RUNNING", "10") or 10)
    REVENUE_ENGINE_LIVE_MAX_QUEUE_TOTAL: int = int(os.getenv("REVENUE_ENGINE_LIVE_MAX_QUEUE_TOTAL", "40") or 40)
    REVENUE_ENGINE_LIVE_MAX_QUEUE_FAIL_RATE: float = float(os.getenv("REVENUE_ENGINE_LIVE_MAX_QUEUE_FAIL_RATE", "0.0") or 0.0)
    REVENUE_ENGINE_LIVE_FAIL_RATE_MIN_TOTAL: int = int(os.getenv("REVENUE_ENGINE_LIVE_FAIL_RATE_MIN_TOTAL", "1") or 1)
    REVENUE_ENGINE_LIVE_MAX_QUEUED_AGE_SEC: int = int(os.getenv("REVENUE_ENGINE_LIVE_MAX_QUEUED_AGE_SEC", "0") or 0)
    REVENUE_ENGINE_LIVE_MAX_RUNNING_AGE_SEC: int = int(os.getenv("REVENUE_ENGINE_LIVE_MAX_RUNNING_AGE_SEC", "0") or 0)
    REVENUE_ENGINE_LIVE_REQUIRE_QUEUE_STATS: bool = os.getenv("REVENUE_ENGINE_LIVE_REQUIRE_QUEUE_STATS", "true").lower() in ("1", "true", "yes", "on")
    REVENUE_ENGINE_LIVE_REQUIRE_BROWSER_RUNTIME: bool = os.getenv("REVENUE_ENGINE_LIVE_REQUIRE_BROWSER_RUNTIME", "false").lower() in ("1", "true", "yes", "on")
    BROWSER_AUTOMATION_ENGINE: str = os.getenv("BROWSER_AUTOMATION_ENGINE", "auto")
    BROWSER_PROXY_POOL: str = os.getenv("BROWSER_PROXY_POOL", "")
    BROWSER_PROXY_COOLDOWN_SEC: int = int(os.getenv("BROWSER_PROXY_COOLDOWN_SEC", "900"))
    REVENUE_ENGINE_LIVE_REQUIRE_SESSION_COOKIE: bool = os.getenv("REVENUE_ENGINE_LIVE_REQUIRE_SESSION_COOKIE", "false").lower() in ("1", "true", "yes", "on")
    GUMROAD_SESSION_COOKIE_FILE: str = os.getenv("GUMROAD_SESSION_COOKIE_FILE", "/tmp/gumroad_cookie.txt")
    REVENUE_ENGINE_PUBLISH_TIMEOUT_SEC: int = int(os.getenv("REVENUE_ENGINE_PUBLISH_TIMEOUT_SEC", "45") or 45)
    REVENUE_ENGINE_AUTO_REPORT_ENABLED: bool = os.getenv("REVENUE_ENGINE_AUTO_REPORT_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    REVENUE_ENGINE_REPORT_DIR: str = os.getenv("REVENUE_ENGINE_REPORT_DIR", "runtime/reports/revenue")
    SELF_HEALER_QUARANTINE_SEC: int = int(os.getenv("SELF_HEALER_QUARANTINE_SEC", "600") or 600)
    SELF_HEALER_QUARANTINE_MAX_MULT: int = int(os.getenv("SELF_HEALER_QUARANTINE_MAX_MULT", "3") or 3)
    SELF_HEALER_MAX_CHANGED_FILES: int = int(os.getenv("SELF_HEALER_MAX_CHANGED_FILES", "12") or 12)
    SELF_HEALER_MAX_CHANGED_LINES: int = int(os.getenv("SELF_HEALER_MAX_CHANGED_LINES", "1200") or 1200)
    SELF_HEALER_POLICY_MODE: str = os.getenv("SELF_HEALER_POLICY_MODE", "balanced")
    SELF_HEALER_BALANCED_ALLOW_SERVICE_RESTART: bool = os.getenv("SELF_HEALER_BALANCED_ALLOW_SERVICE_RESTART", "false").lower() in ("1", "true", "yes", "on")
    SELF_HEALER_CANARY_ENABLED: bool = os.getenv("SELF_HEALER_CANARY_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    SELF_HEALER_CANARY_COMMAND: str = os.getenv("SELF_HEALER_CANARY_COMMAND", "systemctl is-active vito")
    QUALITY_JUDGE_APPROVAL_THRESHOLD: int = int(os.getenv("QUALITY_JUDGE_APPROVAL_THRESHOLD", "7") or 7)
    AUTONOMOUS_IMPROVEMENT_ENABLED: bool = os.getenv("AUTONOMOUS_IMPROVEMENT_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    AUTONOMOUS_IMPROVEMENT_ALERTS_ENABLED: bool = os.getenv("AUTONOMOUS_IMPROVEMENT_ALERTS_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    AUTONOMOUS_IMPROVEMENT_INTERVAL_TICKS: int = int(os.getenv("AUTONOMOUS_IMPROVEMENT_INTERVAL_TICKS", "288") or 288)
    AUTONOMOUS_IMPROVEMENT_MAX_CANDIDATES: int = int(os.getenv("AUTONOMOUS_IMPROVEMENT_MAX_CANDIDATES", "4") or 4)

    # Dashboard
    DASHBOARD_ENABLED: bool = os.getenv("DASHBOARD_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    DASHBOARD_HOST: str = os.getenv("DASHBOARD_HOST", "0.0.0.0")
    DASHBOARD_PORT: int = int(os.getenv("DASHBOARD_PORT", "8787"))
    DASHBOARD_TOKEN: str = os.getenv("DASHBOARD_TOKEN", "")
    PROCESS_GUARD_ENABLED: bool = os.getenv("PROCESS_GUARD_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    PROCESS_GUARD_INTERVAL_SEC: int = int(os.getenv("PROCESS_GUARD_INTERVAL_SEC", "90") or 90)

    # Time sync
    TIME_SYNC_URL: str = os.getenv("TIME_SYNC_URL", "https://worldtimeapi.org/api/ip")
    TIME_SYNC_URLS: str = os.getenv("TIME_SYNC_URLS", "")
    TIME_SYNC_MAX_SKEW_SEC: int = int(os.getenv("TIME_SYNC_MAX_SKEW_SEC", "5"))

    # Calendar update
    CALENDAR_UPDATE_LLM: bool = os.getenv("CALENDAR_UPDATE_LLM", "false").lower() in ("1", "true", "yes", "on")

    # Workflow resume
    RESUME_FROM_CHECKPOINT: bool = os.getenv("RESUME_FROM_CHECKPOINT", "false").lower() in ("1", "true", "yes", "on")
    AUTO_RESUME_MAX_PER_INTERRUPT: int = int(os.getenv("AUTO_RESUME_MAX_PER_INTERRUPT", "6") or 6)
    AUTO_RESUME_COOLDOWN_SEC: int = int(os.getenv("AUTO_RESUME_COOLDOWN_SEC", "10") or 10)
    MEMORY_WEEKLY_REPORT_ENABLED: bool = os.getenv("MEMORY_WEEKLY_REPORT_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    MEMORY_WEEKLY_REPORT_ALERTS_ENABLED: bool = os.getenv("MEMORY_WEEKLY_REPORT_ALERTS_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    MEMORY_WEEKLY_REPORT_INTERVAL_TICKS: int = int(os.getenv("MEMORY_WEEKLY_REPORT_INTERVAL_TICKS", "2016") or 2016)
    MEMORY_CONSOLIDATION_ENABLED: bool = os.getenv("MEMORY_CONSOLIDATION_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    MEMORY_CONSOLIDATION_INTERVAL_TICKS: int = int(os.getenv("MEMORY_CONSOLIDATION_INTERVAL_TICKS", "288") or 288)
    MEMORY_CONSOLIDATION_MIN_AGE_DAYS: int = int(os.getenv("MEMORY_CONSOLIDATION_MIN_AGE_DAYS", "5") or 5)
    MEMORY_CONSOLIDATION_LIMIT: int = int(os.getenv("MEMORY_CONSOLIDATION_LIMIT", "25") or 25)
    CONTENT_AB_EXPERIMENTS_ENABLED: bool = os.getenv("CONTENT_AB_EXPERIMENTS_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    MEMORY_WEEKLY_REPORT_MIN_QUALITY: float = float(os.getenv("MEMORY_WEEKLY_REPORT_MIN_QUALITY", "0.65") or 0.65)
    MEMORY_WEEKLY_REPORT_MIN_SKILL_HEALTH: float = float(os.getenv("MEMORY_WEEKLY_REPORT_MIN_SKILL_HEALTH", "0.55") or 0.55)
    MEMORY_WEEKLY_REPORT_PATH: str = os.getenv("MEMORY_WEEKLY_REPORT_PATH", "reports/memory_retention_weekly.md")
    WEEKLY_GOVERNANCE_REPORT_ENABLED: bool = os.getenv("WEEKLY_GOVERNANCE_REPORT_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    WEEKLY_GOVERNANCE_REPORT_ALERTS_ENABLED: bool = os.getenv("WEEKLY_GOVERNANCE_REPORT_ALERTS_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    WEEKLY_GOVERNANCE_REPORT_INTERVAL_TICKS: int = int(os.getenv("WEEKLY_GOVERNANCE_REPORT_INTERVAL_TICKS", "2016") or 2016)
    WEEKLY_GOVERNANCE_REPORT_PATH: str = os.getenv("WEEKLY_GOVERNANCE_REPORT_PATH", "reports/governance_weekly.md")
    WEEKLY_GOVERNANCE_SKILL_REMEDIATE_ENABLED: bool = os.getenv("WEEKLY_GOVERNANCE_SKILL_REMEDIATE_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    WEEKLY_GOVERNANCE_SKILL_REMEDIATE_LIMIT: int = int(os.getenv("WEEKLY_GOVERNANCE_SKILL_REMEDIATE_LIMIT", "20") or 20)
    WEEKLY_GOVERNANCE_AUTO_REMEDIATE: bool = os.getenv("WEEKLY_GOVERNANCE_AUTO_REMEDIATE", "false").lower() in ("1", "true", "yes", "on")
    WEEKLY_GOVERNANCE_AUTO_REMEDIATE_ON_WARNING: bool = os.getenv("WEEKLY_GOVERNANCE_AUTO_REMEDIATE_ON_WARNING", "false").lower() in ("1", "true", "yes", "on")
    WEEKLY_GOVERNANCE_AUTO_REMEDIATE_MAX_ACTIONS: int = int(os.getenv("WEEKLY_GOVERNANCE_AUTO_REMEDIATE_MAX_ACTIONS", "2") or 2)
    SELF_REFINE_ENABLED: bool = os.getenv("SELF_REFINE_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    SELF_REFINE_MAX_PASSES: int = int(os.getenv("SELF_REFINE_MAX_PASSES", "1") or 1)
    SELF_LEARNING_ENABLED: bool = os.getenv("SELF_LEARNING_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    SELF_LEARNING_SKILL_SCORE_MIN: float = float(os.getenv("SELF_LEARNING_SKILL_SCORE_MIN", "0.78") or 0.78)
    SELF_LEARNING_AUTO_PROMOTE: bool = os.getenv("SELF_LEARNING_AUTO_PROMOTE", "false").lower() in ("1", "true", "yes", "on")
    SELF_LEARNING_MIN_LESSONS: int = int(os.getenv("SELF_LEARNING_MIN_LESSONS", "3") or 3)
    SELF_LEARNING_OPTIMIZE_INTERVAL_TICKS: int = int(os.getenv("SELF_LEARNING_OPTIMIZE_INTERVAL_TICKS", "72") or 72)
    SELF_LEARNING_TEST_RUNNER_ENABLED: bool = os.getenv("SELF_LEARNING_TEST_RUNNER_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    SELF_LEARNING_TEST_RUNNER_INTERVAL_TICKS: int = int(os.getenv("SELF_LEARNING_TEST_RUNNER_INTERVAL_TICKS", "96") or 96)
    SELF_LEARNING_TEST_RUNNER_MAX_JOBS: int = int(os.getenv("SELF_LEARNING_TEST_RUNNER_MAX_JOBS", "2") or 2)
    SELF_LEARNING_TEST_RUNNER_TIMEOUT_SEC: int = int(os.getenv("SELF_LEARNING_TEST_RUNNER_TIMEOUT_SEC", "120") or 120)
    SELF_LEARNING_MAINTENANCE_INTERVAL_TICKS: int = int(os.getenv("SELF_LEARNING_MAINTENANCE_INTERVAL_TICKS", "168") or 168)
    SELF_LEARNING_MAINTENANCE_DAYS: int = int(os.getenv("SELF_LEARNING_MAINTENANCE_DAYS", "45") or 45)
    SELF_LEARNING_MAINTENANCE_MIN_LESSONS: int = int(os.getenv("SELF_LEARNING_MAINTENANCE_MIN_LESSONS", "4") or 4)
    SELF_LEARNING_REMEDIATION_MAX_ACTIONS: int = int(os.getenv("SELF_LEARNING_REMEDIATION_MAX_ACTIONS", "3") or 3)
    SELF_LEARNING_TEST_JOB_RETENTION_DAYS: int = int(os.getenv("SELF_LEARNING_TEST_JOB_RETENTION_DAYS", "90") or 90)
    SELF_LEARNING_TEST_RETRY_ON_FAIL: bool = os.getenv("SELF_LEARNING_TEST_RETRY_ON_FAIL", "true").lower() in ("1", "true", "yes", "on")
    SELF_LEARNING_TEST_MAX_ATTEMPTS: int = int(os.getenv("SELF_LEARNING_TEST_MAX_ATTEMPTS", "2") or 2)
    SELF_LEARNING_FLAKY_COOLDOWN_HOURS: int = int(os.getenv("SELF_LEARNING_FLAKY_COOLDOWN_HOURS", "72") or 72)
    SELF_LEARNING_FLAKY_RATE_MAX: float = float(os.getenv("SELF_LEARNING_FLAKY_RATE_MAX", "0.3") or 0.3)
    SELF_LEARNING_FLAKY_WINDOW_DAYS: int = int(os.getenv("SELF_LEARNING_FLAKY_WINDOW_DAYS", "30") or 30)
    SELF_LEARNING_FLAKY_DECAY_DAYS: int = int(os.getenv("SELF_LEARNING_FLAKY_DECAY_DAYS", "14") or 14)
    SELF_LEARNING_FLAKY_MIN_WEIGHT: float = float(os.getenv("SELF_LEARNING_FLAKY_MIN_WEIGHT", "0.12") or 0.12)
    SELF_LEARNING_OUTCOME_WINDOW_DAYS: int = int(os.getenv("SELF_LEARNING_OUTCOME_WINDOW_DAYS", "60") or 60)
    SELF_LEARNING_OUTCOME_DECAY_DAYS: int = int(os.getenv("SELF_LEARNING_OUTCOME_DECAY_DAYS", "21") or 21)
    SELF_LEARNING_THRESHOLD_OUTCOME_WEIGHT: float = float(os.getenv("SELF_LEARNING_THRESHOLD_OUTCOME_WEIGHT", "0.02") or 0.02)
    SELF_LEARNING_OUTCOME_MIN_TEST_RUNS: int = int(os.getenv("SELF_LEARNING_OUTCOME_MIN_TEST_RUNS", "2") or 2)
    SELF_LEARNING_OUTCOME_FAIL_RATE_MAX: float = float(os.getenv("SELF_LEARNING_OUTCOME_FAIL_RATE_MAX", "0.35") or 0.35)
    SELF_LEARNING_TEST_TARGET_MAP: str = os.getenv("SELF_LEARNING_TEST_TARGET_MAP", "")

    # Owner preference auto-detect (off by default)
    OWNER_PREF_AUTO_DETECT: bool = os.getenv("OWNER_PREF_AUTO_DETECT", "false").lower() in ("1", "true", "yes", "on")

    # Capability pack gating
    CAPABILITY_PACK_ALLOW_PENDING: bool = os.getenv("CAPABILITY_PACK_ALLOW_PENDING", "false").lower() in ("1", "true", "yes", "on")

    # LLM guardrails
    GUARDRAILS_ENABLED: bool = os.getenv("GUARDRAILS_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    GUARDRAILS_BLOCK_ON_INJECTION: bool = os.getenv("GUARDRAILS_BLOCK_ON_INJECTION", "true").lower() in ("1", "true", "yes", "on")
    LLM_ALERTS_ENABLED: bool = os.getenv("LLM_ALERTS_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    TOOLING_RUN_LIVE_ENABLED: bool = os.getenv("TOOLING_RUN_LIVE_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    TOOLING_HTTP_TIMEOUT_SEC: int = int(os.getenv("TOOLING_HTTP_TIMEOUT_SEC", "8") or 8)
    TOOLING_MCP_TIMEOUT_SEC: int = int(os.getenv("TOOLING_MCP_TIMEOUT_SEC", "12") or 12)
    TOOLING_MCP_MAX_OUTPUT_BYTES: int = int(os.getenv("TOOLING_MCP_MAX_OUTPUT_BYTES", "32768") or 32768)
    TOOLING_MCP_ALLOW_CMDS: str = os.getenv("TOOLING_MCP_ALLOW_CMDS", "python3,node,npx,uv,mcp-server")
    TOOLING_CONTRACT_SECRET: str = os.getenv("TOOLING_CONTRACT_SECRET", "tooling-contract-local")
    TOOLING_CONTRACT_KEYS: str = os.getenv("TOOLING_CONTRACT_KEYS", "")
    TOOLING_CONTRACT_ACTIVE_KEY_ID: str = os.getenv("TOOLING_CONTRACT_ACTIVE_KEY_ID", "")
    TOOLING_BLOCK_WITH_PENDING_ROTATION: bool = os.getenv("TOOLING_BLOCK_WITH_PENDING_ROTATION", "true").lower() in ("1", "true", "yes", "on")
    TOOLING_LIVE_REQUIRED_STAGE: str = os.getenv("TOOLING_LIVE_REQUIRED_STAGE", "production")
    TOOLING_REQUIRE_PRODUCTION_APPROVAL: bool = os.getenv("TOOLING_REQUIRE_PRODUCTION_APPROVAL", "true").lower() in ("1", "true", "yes", "on")
    TOOLING_REQUIRE_ROLLBACK_APPROVAL: bool = os.getenv("TOOLING_REQUIRE_ROLLBACK_APPROVAL", "true").lower() in ("1", "true", "yes", "on")
    TOOLING_KEY_ROTATION_MAX_DAYS: int = int(os.getenv("TOOLING_KEY_ROTATION_MAX_DAYS", "90") or 90)
    TOOLING_KEY_ROTATION_WARN_DAYS: int = int(os.getenv("TOOLING_KEY_ROTATION_WARN_DAYS", "14") or 14)
    TOOLING_GOVERNANCE_ALERT_ENABLED: bool = os.getenv("TOOLING_GOVERNANCE_ALERT_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    TOOLING_GOVERNANCE_INTERVAL_TICKS: int = int(os.getenv("TOOLING_GOVERNANCE_INTERVAL_TICKS", "288") or 288)
    TOOLING_DISCOVERY_ENABLED: bool = os.getenv("TOOLING_DISCOVERY_ENABLED", "false").lower() in ("1", "true", "yes", "on")
    TOOLING_DISCOVERY_ALERTS_ENABLED: bool = os.getenv("TOOLING_DISCOVERY_ALERTS_ENABLED", "true").lower() in ("1", "true", "yes", "on")
    TOOLING_DISCOVERY_INTERVAL_TICKS: int = int(os.getenv("TOOLING_DISCOVERY_INTERVAL_TICKS", "288") or 288)
    TOOLING_DISCOVERY_MAX_PER_TICK: int = int(os.getenv("TOOLING_DISCOVERY_MAX_PER_TICK", "3") or 3)
    TOOLING_DISCOVERY_AUTO_PROMOTE_APPROVED: bool = os.getenv("TOOLING_DISCOVERY_AUTO_PROMOTE_APPROVED", "false").lower() in ("1", "true", "yes", "on")
    TOOLING_DISCOVERY_DEDUP_HOURS: int = int(os.getenv("TOOLING_DISCOVERY_DEDUP_HOURS", "72") or 72)
    TOOLING_DISCOVERY_ROLLOUT_STAGE: str = os.getenv("TOOLING_DISCOVERY_ROLLOUT_STAGE", "canary")
    TOOLING_DISCOVERY_CANARY_PERCENT: int = int(os.getenv("TOOLING_DISCOVERY_CANARY_PERCENT", "34") or 34)
    TOOLING_DISCOVERY_REQUIRE_HTTPS: bool = os.getenv("TOOLING_DISCOVERY_REQUIRE_HTTPS", "true").lower() in ("1", "true", "yes", "on")
    TOOLING_DISCOVERY_ALLOWED_DOMAINS: str = os.getenv("TOOLING_DISCOVERY_ALLOWED_DOMAINS", "")
    TOOLING_DISCOVERY_AUTO_PAUSE_ON_POLICY_BLOCK: bool = os.getenv("TOOLING_DISCOVERY_AUTO_PAUSE_ON_POLICY_BLOCK", "false").lower() in ("1", "true", "yes", "on")
    TOOLING_DISCOVERY_POLICY_BLOCK_THRESHOLD: int = int(os.getenv("TOOLING_DISCOVERY_POLICY_BLOCK_THRESHOLD", "3") or 3)
    TOOLING_DISCOVERY_POLICY_BLOCK_RATE_THRESHOLD: float = float(os.getenv("TOOLING_DISCOVERY_POLICY_BLOCK_RATE_THRESHOLD", "0.8") or 0.8)
    TOOLING_DISCOVERY_POLICY_BLOCK_RATE_MIN_PROCESSED: int = int(os.getenv("TOOLING_DISCOVERY_POLICY_BLOCK_RATE_MIN_PROCESSED", "3") or 3)
    TOOLING_DISCOVERY_SOURCES: str = os.getenv("TOOLING_DISCOVERY_SOURCES", "")
    TOOLING_RELEASE_SECRET: str = os.getenv("TOOLING_RELEASE_SECRET", "tooling-release-local")
    TOOLING_RELEASE_KEYS: str = os.getenv("TOOLING_RELEASE_KEYS", "")
    TOOLING_RELEASE_ACTIVE_KEY_ID: str = os.getenv("TOOLING_RELEASE_ACTIVE_KEY_ID", "")


settings = Settings()
