#!/usr/bin/env python3
"""Unified Gumroad publish pipeline.

Use this script instead of legacy gumroad_fix*/gumroad_tags* helpers.
"""

from __future__ import annotations

import argparse
import asyncio
from pathlib import Path

from config.paths import PROJECT_ROOT
from platforms.gumroad import GumroadPlatform


def _latest(path: Path, pattern: str) -> str:
    files = list(path.glob(pattern))
    if not files:
        return ""
    files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return str(files[0])


async def run(args: argparse.Namespace) -> int:
    root = Path(args.root).resolve()
    out = root / "output"
    payload = {
        "name": args.name,
        "price": args.price,
        "description": args.description,
        "summary": args.summary,
        "pdf_path": args.pdf or _latest(out, "products/*.pdf"),
        "cover_path": args.cover or _latest(out, "images/cover_*"),
        "thumb_path": args.thumb or _latest(out, "images/thumb_*"),
        "draft_only": bool(args.draft_only),
        "dry_run": bool(args.dry_run),
    }
    platform = GumroadPlatform()
    result = await platform.publish(payload)
    await platform.close()
    print(result)
    return 0 if result.get("status") in {"prepared", "published", "draft"} else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Unified Gumroad pipeline")
    parser.add_argument("--root", default=str(PROJECT_ROOT), help="Project root")
    parser.add_argument("--name", required=True, help="Product name")
    parser.add_argument("--price", type=int, default=9, help="Price in USD")
    parser.add_argument("--description", default="VITO product", help="Description")
    parser.add_argument("--summary", default="Generated by VITO", help="Summary")
    parser.add_argument("--pdf", default="", help="Path to PDF")
    parser.add_argument("--cover", default="", help="Path to cover image")
    parser.add_argument("--thumb", default="", help="Path to thumbnail image")
    parser.add_argument("--dry-run", action="store_true", help="Validate only")
    parser.add_argument("--draft-only", action="store_true", help="Create draft without final publish")
    args = parser.parse_args()
    return asyncio.run(run(args))


if __name__ == "__main__":
    raise SystemExit(main())
